# Generated by Django 5.2.8 on 2025-11-17 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"verbose_name": "Todo Task", "verbose_name_plural": "Todo Tasks"},
        ),
    ]
