# Generated by Django 5.2.8 on 2025-11-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-deadline"],
                "verbose_name": "Todo Task",
                "verbose_name_plural": "Todo Tasks",
            },
        ),
    ]
